name: Run tests

on:
  pull_request:
  workflow_call:

permissions:
  contents: read

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Use Node
        uses: actions/setup-node@v4
        with:
          cache: 'npm'
          node-version: 20.18.0
      - name: Start server
        run: npm start
      - name: Run tests
        run: npm test
